apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sync-to-s3
  namespace: utilities
spec:
  schedule: "*/10 * * * *" # example: every 10 minutes
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 10
  jobTemplate:
      spec:
        activeDeadlineSeconds: 3300 # example: after 55 minutes
        template:
          spec:
            restartPolicy: "OnFailure"
            containers:
            - name: sync-to-s3
              image: pierreros/sync-folder-to-s3:develop
              env:
              - name: ACCESS_KEY
                value: xyz
              - name: SECRET_KEY
                value: xyz
              - name: S3_PATH
                value: xyz
              - name: DATA_PATH
                value: /data/
              volumeMounts:
              - name: volume-to-sync
                mountPath: /data
            volumes:
            - name: volume-to-sync
              persistentVolumeClaim:
                claimName: volume-to-sync
